### ISSUE TITLE
Use React for lantern frontend

### ISSUE THREAD

**Issue by sabaimran** [khoj-ai/lantern#11]
Add front end code to Lantern and serve it with the Django backend

Potentially useful tutorials:
- https://dev.to/zachtylr21/how-to-serve-a-react-single-page-app-with-django-1a1l
- https://www.digitalocean.com/community/tutorials/build-a-to-do-application-using-django-and-react

The responsibilities of this front-end application should essentially encompass login and logout. See the login/set password pages in the landing page for reference. https://github.com/khoj-ai/landing-page/pull/12

**Comment by debanjum** [comment]
Deploy React production build in Django app: https://medium.com/codex/deploying-react-through-djangos-static-files-part-1-dev-setup-8a3a7b93c809
